project/apps/accounts/urls.py
from django.urls import path
from . import views, redirects


app_name = 'accounts'
urlpatterns = []


PATHS = [
    # Authentication
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # Activation
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('activate/email/<to_email>/', views.activation_send, name='activation_send'),
    path('activate/success/', views.activation_success, name='activation_success'),
    path('activate/fail/', views.activation_fail, name='activation_fail'),

    # Password management
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('reset-password/<uidb64>/<token>/', views.reset, name='reset'),
    path('reset-password/email/<to_email>/', views.reset_password_send, name='reset_password_send'),
    path('reset-password/success/', views.reset_password_success, name='reset_password_success'),
    path('reset-password/fail/', views.reset_password_fail, name='reset_password_fail'),
]

REDIRECTS = [
    path('', redirects.login),
]


urlpatterns += PATHS
urlpatterns += REDIRECTS

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    nickname = models.CharField(max_length=150, null=True, blank=True)
    first_name = None
    last_name = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self) -> str:
        return self.username

project/apps/accounts/forms.py
from django.http import HttpRequest
from . import models

# Mailing imports
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from . import tokens

# Form creation imports
from django import forms
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm, PasswordResetForm
from django.contrib.auth import get_user_model


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):  
    email = forms.EmailField(max_length=200, help_text='Required')  

    class Meta:  
        model = get_user_model() 
        fields = [
            'username',
            'nickname',
            'email',
            'password1',
            'password2'
        ]

    def save(self, commit=True):
        user = super().save(commit=False)

        nickname = self.cleaned_data.get('nickname')
        if not nickname:
            username = self.cleaned_data.get('username')
            user.nickname = username

        if commit:
            user.save()

        return user
    
    def send_email_activation(self, request: HttpRequest,) -> models.User:
        user = self.save(commit=False)
        user.is_active = False
        user.save()

        subject = '' # TODO: Add subject
        message = render_to_string('accounts/activation-email.html', {
            'user': user,
            'domain': get_current_site(request).domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': tokens.account_activation_token.make_token(user),
            'protocol': 'https' if request.is_secure() else 'http',
        })
        to_email = self.cleaned_data.get('email')
        email = EmailMessage(subject, message, to=[to_email])
        email.send()

        return user


class ChangePasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']


class PasswordResetForm(PasswordResetForm):
    def send_password_reset(self, request: HttpRequest) -> None:
        email = self.cleaned_data.get('email')
        user = get_user_model().objects.filter(email=email).first()
        if user:
            subject = '' # TODO: Add subject
            message = render_to_string('accounts/reset-password-email.html', {
                'user': user,
                'domain': get_current_site(request).domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': tokens.account_activation_token.make_token(user),
                'protocol': 'https' if request.is_secure() else 'http',
            })
            email = EmailMessage(subject, message, to=[email])
            email.send()
        
        return user

project/apps/accounts/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect

# Authentication imports
from django.contrib import auth
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# Activation imports
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from .tokens import account_activation_token

# Views imports
from django.shortcuts import render, redirect
from utils.views import get_template
from . import urls, forms



# Authentication
def login(request: HttpRequest) -> HttpResponse:
    template = get_template(app=urls.app_name)

    if request.method == 'GET':
        form = forms.LoginForm()

    if request.method == 'POST':
        form = forms.LoginForm(request.POST) 
        if form.is_valid():
            user = auth.authenticate(request,
                username=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password'),
            )
            if user:
                auth.login(request, user)
                return redirect('/') #TODO: Add after login destination

    return render(request, template, {
        'form': form
    })


@login_required
def logout(request):
    auth.logout(request)
    return redirect('accounts:login')


# Activation
def register(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    template = get_template(app=urls.app_name)

    if request.method == 'GET':
        form = forms.RegisterForm()

    if request.method == 'POST': 
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            user = form.send_email_activation(request)
            request.session['activation'] = True
            return redirect('accounts:activation_send', to_email=user.email)

    return render(request, template, {
        'form': form
    })


def activation_send(request: HttpRequest, to_email: str) -> HttpResponse | HttpResponseRedirect:
    if request.session.get('activation') == False:
        return redirect('accounts:login')

    template = get_template(app=urls.app_name)
    return render(request, template, {
        'to_email': to_email,
    })


def activate(request: HttpRequest, uidb64: str, token: str) -> HttpResponseRedirect:
    if request.session.get('activation') == False:
        return redirect('accounts:login')
    
    User = get_user_model()

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('accounts:activation_success')
    return redirect('accounts:activation_fail')


def activation_success(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.session.get('activation') == False:
        return redirect('accounts:login')

    request.session['activation'] = False
    template = get_template(app=urls.app_name)

    return render(request, template)


def activation_fail(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.session.get('activation') == False:
        return redirect('accounts:login')

    request.session['activation'] = False
    template = get_template(app=urls.app_name)

    return render(request, template)


# Password management
@login_required
def change_password(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    template = get_template(app=urls.app_name)
    user = request.user

    if request.method == 'GET':
        form = forms.ChangePasswordForm(user)

    if request.method == 'POST':
        form = forms.ChangePasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')

    return render(request, template, {
        'form': form
    })


def reset_password(request: HttpRequest) -> HttpResponse:
    template = get_template(app=urls.app_name)
    if request.method == 'GET':
        form = forms.PasswordResetForm()

    if request.method == 'POST':
        form = forms.PasswordResetForm(request.POST)
        if form.is_valid():
            user = form.send_password_reset(request)
            request.session['reset'] = True
            return redirect('accounts:reset_password_send', to_email=user.email)


    return render(request, template, {
        'form': form,
    })


def reset_password_send(request: HttpRequest, to_email: str) -> HttpResponse | HttpResponseRedirect:
    if request.session.get('reset') == False:
        return redirect('accounts:login')

    template = get_template(app=urls.app_name)
    return render(request, template, {
        'to_email': to_email,
    })


def reset(request: HttpRequest, uidb64: str, token: str) -> HttpResponse | HttpResponseRedirect:
    if request.session.get('reset') == False:
        return redirect('accounts:login')
    
    User = get_user_model()

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if request.method == 'GET':
        form = forms.ChangePasswordForm(user)

    if request.method == 'POST':
        if user and account_activation_token.check_token(user, token):
            form = forms.ChangePasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                return redirect('accounts:reset_password_success')
        return redirect('accounts:reset_password_fail')
    
    template = get_template(app=urls.app_name)
    return render(request, template, {
        'form': form,
    })


def reset_password_success(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.session.get('reset') == False:
        return redirect('accounts:login')

    request.session['reset'] = False
    template = get_template(app=urls.app_name)

    return render(request, template)


def reset_password_fail(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.session.get('reset') == False:
        return redirect('accounts:login')

    request.session['reset'] = False
    template = get_template(app=urls.app_name)

    return render(request, template)

project/templates/accounts/activation-email.html
{% autoescape off %}  
Hi {{ user.nickname }},  
Please click on the link to confirm your registration,  
{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}  
{% endautoescape %}  

project/templates/accounts/activation-fail.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/activation-fail.css' %}">
{% endblock static %}


{% block content %}
Fail!
{% endblock content %}

project/templates/accounts/activation-send.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/activation-send.css' %}">
{% endblock static %}


{% block content %}
{% endblock content %}

project/templates/accounts/activation-succes.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/activation-succes.css' %}">
{% endblock static %}


{% block content %}
{% endblock content %}

project/templates/accounts/base.html
{% extends 'global/base.html' %}


{% block base_static %}
  {% block static %}
  {% endblock static %}
{% endblock base_static %}


{% block base_content %}
  {% block content %}
  {% endblock content %}
{% endblock base_content %}

project/templates/accounts/change-password.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/change-password.css' %}">
{% endblock static %}


{% block content %}
{{ user.email }}

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Change Password">
</form>
{% endblock content %}

project/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/login.css' %}">
{% endblock static %}


{% block content %}
{{ user.email }}

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Login">
</form>
{% endblock content %}

project/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/register.css' %}">
{% endblock static %}


{% block content %}
{% endblock content %}

project/templates/accounts/reset-password-email.html
{% autoescape off %}
Hello {{ user.nickname }},

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'accounts:reset' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

If you did not make this request, you can simply ignore this email.
{% endautoescape %}

project/templates/accounts/reset-password-fail.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/reset-password-fail.css' %}">
{% endblock static %}


{% block content %}
Fail!
{% endblock content %}

project/templates/accounts/reset-password-send.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/reset-password-send.css' %}">
{% endblock static %}


{% block content %}
Email was send to {{ to_email }}
{% endblock content %}

project/templates/accounts/reset-password-success.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/reset-password-success.css' %}">
{% endblock static %}


{% block content %}
Success!
{% endblock content %}

project/templates/accounts/reset-password.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/reset-password.css' %}">
{% endblock static %}


{% block content %}
{{ user.email }}

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Reset Password">
</form>
{% endblock content %}

project/templates/accounts/reset.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'accounts/reset.css' %}">
{% endblock static %}


{% block content %}
{{ user.email }}

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Reset Password">
</form>
{% endblock content %}